### PR TITLE
Use gfx_hal 0.1.0

### PR DESCRIPTION
**Pull request by 64**
`gfx_hal` has finally been published, so I updated rendy to use it. It requires adding unsafe blocks in a number of places.

### CODE REVIEW

**Comment by termhn** [comment]
Thanks! LGTM. Is this `rustfmt`'d?

**Comment by 64** [comment]
Sorry, it's not. I seemed to remember the other PR doing a rustfmt run, but I guess I just imagined that. I'll do it now.

**Comment by 64** [comment]
Oh yeah, the diff is huge - it affects way more files than I've touched. Want me to commit it anyway?

**Comment by termhn** [comment]
Uhh, might as well just do a rustfmt commit later then and leave this as is.

**Pull request merged**
